.github/dependabot.yml

feat: config dependabot version updates

---

.github/dependabot.yml

fix `dependabot.yml` config issue

fix: dependabot config file

---

backend/poetry.lock
backend/pyproject.toml

feat: setup poethepoet task runner with tasks

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature.yml

fix: issue templates with yaml config

---

backend/.gitignore
backend/backend/core/settings.py
backend/poetry.lock
backend/pyproject.toml

configured `django` extended:
- `reset_db`
- `graph_models`
Closes #26

feat: config djnago extensions

---

backend/backend/apps/user/auth.py
backend/backend/apps/user/urls.py
backend/backend/apps/user/views.py
backend/backend/core/exceptions.py
backend/backend/core/settings.py

removed `drf-rest-knox` auth abstraction.

refactor: remove knox auth and use basic token auth

---

.github/CODEOWNERS

chore: update typo in CODEOWNERS file

---

backend/backend/apps/user/serializers.py
backend/backend/apps/user/views.py
backend/backend/apps/user/viewsets.py
backend/backend/core/serializers.py
backend/backend/core/settings.py
backend/backend/core/urls.py
backend/backend/openapi_description.md
backend/poetry.lock
backend/pyproject.toml

feat: re-configure drf-spectacular openapi schema

---

frontend/src/lib/components/header.svelte
frontend/src/lib/components/pages/home/recent_posts.svelte
frontend/src/lib/components/sidebar.svelte
frontend/src/routes/+layout.svelte
frontend/src/routes/+page.svelte

style: new layout structure for large screens

---

backend/django_core/apps/user/api/v1/serializers.py
backend/django_core/apps/user/api/v1/urls.py
backend/django_core/apps/user/api/v1/views.py
backend/django_core/apps/user/api/v1/viewsets.py
backend/django_core/core/settings.py
backend/django_core/core/urls.py
backend/tests/api/v1/user/test_auth.py
backend/tests/api/v1/user/test_me.py
backend/tests/api/v1/user/test_profiles.py
backend/tests/api/v1/user/test_users.py

refactor: integrate namespace versioning

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/modals/modal-auth/forms/join.svelte
frontend/src/lib/schemas/auth.ts
frontend/src/routes/(actions)/auth/+page.server.ts
frontend/src/routes/+layout.server.ts
frontend/src/styles/app.css

feat: integrate superforms features

---

frontend/src/lib/constants/limits.ts
frontend/src/lib/modals/modal-auth/forms/profile-select.svelte

split up codes and move magic numbers to constants.
clean `onMount` body for code splitting.

refactor: code split and refactor profile-select component

---

frontend/src/lib/modals/modal-create-community/forms/introduction.svelte

Removes manual validation of forms with zod, and use superforms features such as validators, SPA,..
validates each schema field and updates layout better.
Fixes #157

feat: integrate superforms in community creation modal

---

.github/workflows/thank-you.yml

A github action that says thanks to contributors.

ci(gh-action): create thank-you.yml

---

frontend/src/lib/functions/debounce.ts
frontend/src/lib/modals/modal-create-community/forms/introduction.svelte

send an API request to validate whether entered community name already exists or not.
and validate entire form on component mount.
Fixes # (nil)

fix: validate community name if exists on creation

---

frontend/src/hooks.server.ts
frontend/src/lib/modals/modal-create-community/forms/type.svelte
frontend/src/lib/modals/modal-create-community/index.svelte
frontend/src/routes/(app)/q/[name]/+layout.svelte
frontend/src/routes/(app)/q/[name]/+page.svelte
frontend/src/routes/(app)/q/[name]/posts/[id]/[slug]/+page.svelte
frontend/src/routes/+layout.svelte
frontend/src/routes/api/communities/+server.ts

Finalizing community creation logic on FE. creates a kit api endpoint to access secure cookies and send request to backend with them as headers. and handle response effectively.
Fixes # (nil)

feat: finalize community creation logic

---

frontend/package-lock.json
frontend/src/lib/modals/_utils/history.svelte.ts
frontend/src/lib/modals/modal-create-community/forms/introduction.svelte
frontend/src/lib/modals/modal-create-community/index.svelte
frontend/src/routes/(api)/communities/+server.ts

Send media files as instance of `File` instead of string to server. configure superforms to handle file input validations and more.
error handling for media files.
Fixes #169

feat: upload media as File instance

---

backend/apps/api/serializers/comment/__init__.py
backend/apps/api/viewsets/post/__init__.py
frontend/src/lib/features/comments/components/comment-block.svelte
frontend/src/lib/features/comments/components/comment-box.svelte
frontend/src/lib/features/comments/index.ts
frontend/src/routes/(api)/communities/posts/comments/+server.ts
frontend/src/routes/(app)/q/[name]/posts/[id]/+server.ts
frontend/src/routes/(app)/q/[name]/posts/[id]/[slug]/+page.svelte

Add actions of a typical comment box, such as comment on posts and reply to other comments.
(will enhance with more features in future)
Related to #134

feat: comment-box actions

---

frontend/.env.example
frontend/.gitignore
frontend/src/lib/modals/modal-auth/forms/join.svelte
frontend/src/lib/modals/modal-create-community/forms/topics.svelte
frontend/vite.config.ts

* Fixed overflow (modal-create-community/forms/topic.svelte),
* Fixed support for PNPM (vite.config.ts,.gitignore),
* Updated (.env.example)
* Minor fix on register modal (modal-auth/forms/join.svelte).

chore: minor fixes and QOL improvements.

---

frontend/src/lib/features/posts/components/post-card.svelte

In layout mode- `card`:
In layout mode- `compact`:
Fixes # (nil)

style: post card component redesign

---

backend/apps/api/serializers/post/__init__.py
backend/apps/api/viewsets/post/__init__.py
frontend/src/lib/clients/v1/schema.ts
frontend/src/lib/schemas/post-submit.ts
frontend/src/lib/stores/sidebar.svelte.ts
frontend/src/routes/(app)/q/[name]/+page.svelte
frontend/src/routes/(app)/submit/+page.server.ts
frontend/src/routes/(app)/submit/+page.svelte

WIP :construction: 
Post submit page with `URL.searchParams` level control over submit type.
Closes #132

feat: post submit page

---

backend/apps/api/viewsets/post/__init__.py
backend/apps/post/managers.py
backend/apps/post/models.py

Implemented API for fetching `Best`, `Hot` and `New` variations of posts.
https://github.com/quibble-dev/Quibble/issues/136#issuecomment-2667957852
Closes #136

feat: sort posts by variations to post listing api

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/components/header.svelte
frontend/src/lib/features/auth/components/profile-create.svelte
frontend/src/lib/features/auth/components/profile-select.svelte
frontend/src/routes/(auth)/+layout.svelte
frontend/tailwind.config.ts

Made `(auth)` pages/routes responsive.
use grid layout instead flexbox.
Fixes #211

style: (auth) pages responsive

---

backend/apps/api/views/user/auth.py
backend/apps/api/viewsets/post/__init__.py
backend/apps/post/managers.py
backend/apps/post/models.py
frontend/src/lib/clients/v1/schema.ts
frontend/src/lib/features/posts/components/posts-header.svelte

Algorithm for sorting `top` posts.
continuation of #208 and #136 

feat: `top` sorting algorithm

---

frontend/src/hooks.server.ts
frontend/src/lib/features/auth/components/profile-select.svelte
frontend/src/routes/(auth)/login/+page.svelte
frontend/src/routes/(auth)/register/+page.svelte

Add protection for routes which requires authentication.
Better redirect with `?dest` param.
Fixes #214

fix: prevent access to submit route when not authenticated

---

frontend/src/lib/components/header.svelte
frontend/src/routes/(app)/+page.svelte
frontend/src/routes/(app)/q/[name]/+layout.svelte
frontend/src/routes/(app)/q/[name]/+page.svelte
frontend/src/routes/(app)/submit/+page.svelte

Improved responsive layout.
used multiple " utility classes.

style: improved responsive design

---

frontend/src/lib/pages/q/create/step_1.svelte
frontend/src/lib/pages/q/create/step_2.svelte
frontend/src/lib/pages/q/create/step_3.svelte
frontend/src/lib/pages/q/create/step_4.svelte
frontend/src/lib/schemas/community-create.ts
frontend/src/routes/(app)/q/create/+page.svelte

Pass `$errors` store to steps component(s) and handle them.
error mappin for better navigation on error.
Fixes #223

feat: handle error on community creation form

---

frontend/src/lib/features/comments/schemas.ts
frontend/src/lib/pages/q/create/step_4.svelte
frontend/src/lib/schemas/auth.ts
frontend/src/lib/schemas/community-create.ts
frontend/src/lib/schemas/post-submit.ts

Make zod validation error messages more generic and user-friendly.
(It's AI, don't blame me)
Fixes #241

refactor: zod validation error messages

---

frontend/src/lib/features/posts/components/post-actions.svelte
frontend/src/lib/features/posts/components/post-card.svelte
frontend/src/routes/(app)/q/[name]/posts/[id]/[slug]/+page.svelte

Creates `post-actions` component which handles post related actions such as upvote and downvote.
calls appropriate API for reflecting in db.
Fixes #210

feat: post upvote downvote actions

---

frontend/src/lib/components/header.svelte
frontend/src/lib/features/posts/components/posts-header.svelte

User can logout from accessing profile menu and clicking on 'Log out' button.
reloads the window after successful logout.
Fixes #258

feat: implement FE logout function with menu

---

frontend/src/routes/(auth)/+layout.svelte

Fix (auth) group pages responsiveness issue on mobile devices.
quick fix.
Fixes #261

fix: (auth) pages responsiveness

---

backend/.env.example
backend/.gitignore
backend/core/settings.py
frontend/src/lib/features/auth/components/code.svelte
frontend/src/routes/(auth)/+layout.svelte
frontend/src/routes/(auth)/login/+page.svelte

User gets redirected to verification page after successfully sending verification email, user can enter the received code.
then redirects to login page to try login again.
Closes #263

feat: explicit email verification when not-verified

---

backend/.env.example
backend/core/settings.py

Configure CSRF and CORS allowed & trusted origins from `ALLOWED_HOSTS`.
Fixes #265

fix: configure cors origins from allowed_hosts

---

frontend/src/lib/features/auth/components/index.ts
frontend/src/lib/features/auth/index.ts
frontend/src/routes/(auth)/+layout.svelte
frontend/src/routes/(auth)/login/+page.svelte
frontend/src/routes/(auth)/register/+page.server.ts
frontend/src/routes/(auth)/register/+page.svelte
frontend/src/routes/(auth)/verification/+page.server.ts
frontend/src/routes/(auth)/verification/+page.svelte

Dedicated verification page for better routing and server handling.
the `/verification` accepts email search param.
Fixes # (nil)

refactor!: dedicated verification page

---

frontend/src/hooks.server.ts
frontend/src/lib/components/header.svelte
frontend/src/lib/components/ui/base-modal.svelte
frontend/src/lib/pages/settings/profile/avatar-setting.svelte
frontend/src/lib/pages/settings/profile/banner-setting.svelte
frontend/src/lib/pages/settings/profile/bio-setting.svelte
frontend/src/lib/pages/settings/profile/form-name.svelte
frontend/src/lib/pages/settings/profile/name-setting.svelte
frontend/src/lib/pages/settings/setting-item.svelte
frontend/src/lib/schemas/settings.ts
frontend/src/routes/(app)/settings/+layout.svelte
frontend/src/routes/(app)/settings/+page.svelte
frontend/src/routes/(app)/settings/profile/+page.server.ts
frontend/src/routes/(app)/settings/profile/+page.svelte
frontend/src/routes/(app)/u/[username]/+layout.svelte
frontend/src/styles/app.css

Settings page for managing account and profile related informations.
comes under `/settings/*`
Closes #275

feat: settings profile page

---

frontend/src/lib/features/auth/components/profile-create.svelte
frontend/src/lib/features/auth/components/profile-select.svelte
frontend/src/lib/features/comments/components/comment-box.svelte
frontend/src/lib/pages/q/create/step_3.svelte
frontend/src/routes/(app)/q/create/+page.svelte
frontend/src/routes/(app)/settings/profile/+page.server.ts
frontend/src/routes/(app)/settings/profile/+page.svelte
frontend/src/routes/(app)/submit/+page.svelte
frontend/src/routes/(auth)/login/+page.svelte
frontend/src/routes/(auth)/register/+page.svelte
frontend/src/routes/(auth)/verification/+page.svelte

Remove superforms's `$delayed` store and use `$submitting` instead for instant feedback.
Also refactored some code related to custom store.

refactor!: superforms delayed store

---

backend/apps/api/viewsets/community/__init__.py
backend/apps/api/viewsets/user/__init__.py
frontend/src/lib/functions/format-error-message.ts
frontend/src/lib/functions/string/format-error-message.ts
frontend/src/routes/(app)/q/[name]/+layout.server.ts
frontend/src/routes/(app)/u/[username]/+layout.server.ts

Raise error on Profile not found page.
refactored rendering of error messages with custom HTML bold tag.
Fixes #279

fix: raise 404 error on profile not found with error format handler

---

frontend/src/lib/components/ui/toast/index.ts
frontend/src/lib/components/ui/toast/toast.svelte.ts
frontend/src/lib/components/ui/toast/toaster.svelte
frontend/src/lib/features/auth/components/profile-create.svelte
frontend/src/routes/(app)/u/[username]/+layout.svelte
frontend/src/routes/(auth)/login/+page.svelte
frontend/src/routes/(auth)/register/+page.svelte

Implemented better API for toast system.
Now can call the store with `.send()`, `.error()`, etc.
Fixes #280

refactor: better toast API

---

backend/apps/api/urls.py
backend/apps/api/views/user/__init__.py
frontend/src/lib/api/v1.d.ts
frontend/src/routes/(app)/settings/+page.svelte
frontend/src/routes/(app)/settings/profile/+page.server.ts
frontend/src/routes/(app)/settings/profile/+page.svelte

Dedicated endpoint for user and user_profile.
for user `/u/me` for user profile `/u/me/profile`. with GET and DELETE methods.

feat: delete account endpoint and modal

---

backend/apps/api/viewsets/community/__init__.py
backend/apps/community/filters.py
backend/core/settings.py
frontend/src/lib/api/v1.d.ts
frontend/src/routes/(app)/submit/+page.svelte

Used `django-filters` custom filter-set instead of another viewset action.

refactor!: custom filterset_class for community

---

frontend/src/lib/features/comments/components/comment-actions.svelte
frontend/src/lib/features/comments/components/comment-block.svelte
frontend/src/lib/features/posts/components/post-actions.svelte
frontend/src/routes/(app)/q/[name]/posts/[id]/[slug]/+page.svelte
frontend/src/styles/app.css

User can mark comment as deleted, and backend will handle it based on children availability and more.
Currently doesn't delete children if they are `deleted: true` as well. (maybe in future if needed).

feat: mark comment as deleted by ID

---

README.md

Updates readme.md with latest MVP lauch.
And other sections.

docs: readme with MVP update
